changelog:
  categories:
    - title: "Features & Improvements"
      labels:
        - "feature"
        - "enhancement"
    - title: "Bug Fixes"
      labels:
        - "fix"
        - "bug"
    - title: "Maintenance & Dependencies"
      labels:
        - "chore"
        - "dependencies"
        - "documentation"
